[env:weact_mini_h743vitx]
platform = ststm32
board = weact_mini_h743vitx
framework = arduino
upload_protocol = dfu
monitor_speed = 115200

build_flags =
    -D USBCON
    -D USBD_USE_CDC_IF
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D HAL_SDRAM_MODULE_ENABLED
    -w
    -I include
    -I lib/DaisySP/Source
    -D HAL_I2S_MODULE_ENABLED
    -D HAL_DMA_MODULE_ENABLED

lib_deps =
    electro-smith/DaisySP
    arduino-libraries/MIDIUSB
